# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Just build the thing"
  lane :build do
    ionic(platform: "ios", prod: true)
    match(type: "appstore")
    build_app()
  end
  lane :beta do
    ionic(platform: "ios", prod: true)
    match(type: "appstore")
    build_app()
    upload_to_testflight
  end
end




platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build production release"
  lane :build do
    ionic(
        platform: "android",
        prod: true,
        keystore_path: '../scheduler-certs/google_play/android-release-key.jks',
        keystore_alias: 'my-alias',
        keystore_password: 'scheduler'
    )
    gradle(task: "clean assembleRelease", project_dir: "./platforms/android")
  end

  desc "Deploy new alpha"
  lane :alpha do
    ionic(
        platform: "android",
        prod: true,
        keystore_path: '../scheduler-certs/google_play/android-release-key.jks',
        keystore_alias: 'my-alias',
        keystore_password: 'scheduler'
    )
    gradle(task: "clean assembleRelease", project_dir: "./platforms/android")
    upload_to_play_store(track: 'alpha')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    ionic(
        platform: "android",
        prod: true,
        keystore_path: '../scheduler-certs/google_play/android-release-key.jks',
        keystore_alias: 'my-alias',
        keystore_password: 'scheduler'
    )
    gradle(task: "clean assembleRelease", project_dir: "./platforms/android")
    upload_to_play_store
  end
end
